name: Gemini CLI Agent
on:
  issue_comment:
    types: [created]

jobs:
  gemini-test:
    runs-on: ubuntu-latest
    # `if` を追加して、コメントに「@gemini-cli」が含まれている場合のみ実行するようにします
    if: contains(github.event.comment.body, '@gemini-cli')
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      # 1. ワークフローが実行されたか確認するためのテスト用ステップ
      - name: "Test: Workflow Triggered"
        run: echo "✅ ワークフローは正常に開始されました。"

      # 2. チェックアウト
      - uses: actions/checkout@v4

      # 3. Gemini CLIの実行
      - name: "Run Gemini CLI"
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
