name: Gemini CLI Agent
on:
  issue_comment:
    types: [created]

jobs:
  gemini-final-test:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@gemini-cli')
    steps:
      - name: "Test API Key with curl"
        run: |
          echo "--- APIキーを使って直接Googleのサーバーに問い合わせます ---"
          curl -v "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H 'Content-Type: application/json' \
            -d '{ "contents":[{"parts":[{"text": "こんにちは"}]}]}'
