name: Gemini CLI Agent
on:
  issue_comment:
    types: [created]

jobs:
  gemini:
    runs-on: ubuntu-latest
    # コメントに「@gemini-cli」が含まれている場合のみ実行
    if: contains(github.event.comment.body, '@gemini-cli')
    permissions:
      issues: write # Issueへのコメント書き込みに必要
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          settings: '--model gemini-1.5-flash-latest' # <-- この行で新しいモデルを指定
